CREATE TABLE IF NOT EXISTS users (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    username VARCHAR(50) NOT NULL,
    admin BIT NOT NULL,
    password_hash VARCHAR(50) NOT NULL);


CREATE TABLE IF NOT EXISTS tests (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    subject VARCHAR(50) NOT NULL,
    scoring_system INTEGER NOT NULL DEFAULT 1,
    complexity_level VARCHAR(50) NOT NULL);


CREATE TABLE IF NOT EXISTS questions (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    question VARCHAR(50) NOT NULL,
    correct_answer_id INTEGER NOT NULL);


CREATE TABLE IF NOT EXISTS answers (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    test_answer VARCHAR(50) NOT NULL,
    question_id INTEGER NOT NULL);


CREATE TABLE IF NOT EXISTS test_question (
    test_id INTEGER NOT NULL,
    question_id INTEGER NOT NULL,
    answers_id INTEGER NOT NULL);


CREATE TABLE IF NOT EXISTS results (
    test_id INTEGER NOT NULL,
    user_id INTEGER NOT NULL,
    score INTEGER NOT NULL);